name: Go
on:
  create:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Get TAG env
        run: |
          tag=${{ github.ref }} | sed -E "s/.*v(.*)/\1/g"
          echo $tag
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: GolangCI-Lint
        uses: Mushus/golangci-linter@v1.1.2

      - name: Build
        run: go build -v .

      - name: Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: maksim77/tinkoff_exporter
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ github.ref }}
          tag_semver: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
