name: Go
on:
  create:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get TAG env
        run: |
          echo ${{ github.ref }} > ref.txt 
          tag=`sed -E "s/.*v(.*)/\1/g" ref.txt`
          echo "::set-env name=tag::$tag"

      - name: GolangCI-Lint
        uses: Mushus/golangci-linter@v1.1.2

      - name: Build
        run: go build -v .

      - name: Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: maksim77/tinkoff_exporter
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.tag }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
